#!/bin/bash

#初始化
pathnow=`pwd`
jobname='yhuang'
shname='fluent'
lsfname='fluent'
jouname='fluent-shuntai'
fuentcase='fluent'
number=8
steps=1000
maxits=40
option1=${1}

#定义函数
WriteShfJou(){
	echo -e "case(data):\t${fuentcase}.cas(dat)\nsh file name:\t${shname}.sh\njou file name:\t${jouname}.jou\nbsub name:\t${jobname}\nuse cpu number:\t${number}"
	echo "/solve/dual-time-iterate ${steps} ${maxits}"
	# 写sh文件
	echo "#!/bin/sh" > ${shname}.sh  #第一个为 '>' 表明覆盖,之后为追加
	echo "fluent 2ddp -g -t${number} -i ${pathnow}/${jouname}.jou" >> ${shname}.sh
	# 写jou文件
	echo "/file/read-case ${pathnow}/${fuentcase}.cas" > ${jouname}.jou  #第一个为 '>' 表明覆盖,之后为追加
	echo "/file/read-data ${pathnow}/${fuentcase}.dat" >> ${jouname}.jou
	echo "/solve/dual-time-iterate ${steps} ${maxits}" >> ${jouname}.jou
	echo "exit" >> ${jouname}.jou
	echo "yes" >> ${jouname}.jou
	echo ""
}
WriteLsfJou(){
	echo -e "case(data):\t${fuentcase}.cas(dat)\nlsf file name:\t${lsfname}.lsf\njou file name:\t${jouname}.jou\nbsub name:\t${jobname}\nuse cpu number:\t${number}"
	echo "/solve/dual-time-iterate ${steps} ${maxits}"
	# 写lsf文件
	echo "#!/bin/sh" > ${lsfname}.lsf  #第一个为 '>' 表明覆盖,之后为追加
	echo "#" >> ${lsfname}.lsf
	echo "#BSUB -J ${jobname}" >> ${lsfname}.lsf
	echo "#BSUB -q normal" >> ${lsfname}.lsf
	echo "#BSUB -o %J.out" >> ${lsfname}.lsf
	echo "#BSUB -e %J.err" >> ${lsfname}.lsf
	echo "#BSUB -n ${number}" >> ${lsfname}.lsf
	echo "" >> ${lsfname}.lsf
	echo "module load impi" >> ${lsfname}.lsf
	echo "fluent 2ddp -g -t${number} -i ${pathnow}/${jouname}.jou" >> ${lsfname}.lsf
	# 写jou文件
	echo "/file/read-case ${pathnow}/${fuentcase}.cas" > ${jouname}.jou  #第一个为 '>' 表明覆盖,之后为追加
	echo "/file/read-data ${pathnow}/${fuentcase}.dat" >> ${jouname}.jou
	echo "/solve/dual-time-iterate ${steps} ${maxits}" >> ${jouname}.jou
	echo "exit" >> ${jouname}.jou
	echo "yes" >> ${jouname}.jou
	echo ""
}
usage(){
	echo "usage: vvgenerate [-input] [--help]"
}
printSettings(){
	#读取case名
	echo -n "please input cas(dat)name (empty for 'fluent'):"
	read nametemp
	fuentcase=${nametemp:=fluent}

	#读取job名
	echo -n "please input jobname ('yhuang'):"
	read nametemp
	jobname=${nametemp:=yhuang}

	#读取cpu数
	echo -n "please input cpu number ('8'):"
	read numtemp
	number=${numtemp:=8}

	#读取steps名
	echo -n "please input number of timesteps ('1000'):"
	read numtemp
	steps=${numtemp:=1000}

	#读取maxits名
	echo -n "please input max iterates of one step ('40'):"
	read numtemp
	maxits=${numtemp:=40}
	
	#读取lsf名
	echo -n "please input lsfname ('fluent'):"
	read nametemp
	lsfname=${nametemp:=fluent}
	shname=${lsfname}

	#读取jou名
	echo -n "please input jouname ('fluent-shuntai'):"
	read nametemp
	jouname=${nametemp:=fluent-shuntai}

	echo ""
	echo "you settings is..."
	echo ""
}

#main,从这里开始主程序
case ${option1} in
	-h) usage
		;;
	--help) usage
		;;
	ubuntu) 
		printSettings
		WriteShfJou
		echo `./${shname}.sh`
		;;
	jiqun) 
		printSettings
		WriteLsfJou
		echo `bsub < ${lsfname}.lsf`
		;;
	"") 
		printSettings
		WriteShfJou
		echo "the default is use 'vvg ubuntu'"
		echo "if you want to submit a lsf file, you need type 'bsub < ${lsfname}.lsf' after settings or use 'vvg jiqun'"
		echo ""
		echo "run './${shname}.sh' for calculation"
		;;
	*) 
		echo "Unknown opition: ${option1}"
		usage
		;;
esac

