#!/bin/bash

#初始化
isjiqun=1
istransient=1
pathnow=`pwd`
jobname='yhuang'
shname='fluent'
lsfname='fluent'
jouname='fluent-shuntai'
fluentcase='fluent'
fluentdata='fluent'
is2d3d='2ddp'
number=8
steps=1000
maxits=40
option1=${1}

#定义函数
WriteShfJou(){
	echo -e "case:\t${fluentcase}.cas\ndata:\t${fluentdata}.dat\nsh:\t${shname}.sh\njou:\t${jouname}.jou\ncpu number:\t${number}"
	if [[ ${1} == 1 ]]; then
		echo "/solve/dual-time-iterate ${steps} ${maxits}"
	else	
		echo "/solve/iterate ${steps}"
	fi
	# 写sh文件
	echo "#!/bin/sh" > ${shname}.sh  #第一个为 '>' 表明覆盖,之后为追加
	echo "fluent ${is2d3d} -g -t${number} -i ${pathnow}/${jouname}.jou" >> ${shname}.sh
	# 写jou文件
	echo "/file/read-case ${pathnow}/${fluentcase}.cas" > ${jouname}.jou  #第一个为 '>' 表明覆盖,之后为追加
	echo "/file/read-data ${pathnow}/${fluentdata}.dat" >> ${jouname}.jou
	if [[ ${1} == 1 ]]; then
		echo "/solve/dual-time-iterate ${steps} ${maxits}" >> ${jouname}.jou
	else	
		echo "/solve/iterate ${steps}" >> ${jouname}.jou
	fi
	echo "exit" >> ${jouname}.jou
	echo "yes" >> ${jouname}.jou
	echo ""
}
WriteLsfJou(){
	echo -e "case(data):\t${fluentcase}.cas(dat)\nlsf file name:\t${lsfname}.lsf\njou file name:\t${jouname}.jou\nbsub name:\t${jobname}\nuse cpu number:\t${number}"
	if [[ ${1} == 1 ]]; then
		echo "/solve/dual-time-iterate ${steps} ${maxits}"
	else	
		echo "/solve/iterate ${steps}"
	fi
	# 写lsf文件
	echo "#!/bin/sh" > ${lsfname}.lsf  #第一个为 '>' 表明覆盖,之后为追加
	echo "#" >> ${lsfname}.lsf
	echo "#BSUB -J ${jobname}" >> ${lsfname}.lsf
	echo "#BSUB -q normal" >> ${lsfname}.lsf
	echo "#BSUB -o %J.out" >> ${lsfname}.lsf
	echo "#BSUB -e %J.err" >> ${lsfname}.lsf
	echo "#BSUB -n ${number}" >> ${lsfname}.lsf
	echo "" >> ${lsfname}.lsf
	echo "module load impi" >> ${lsfname}.lsf
	echo "fluent ${is2d3d} -g -t${number} -i ${pathnow}/${jouname}.jou" >> ${lsfname}.lsf
	# 写jou文件
	echo "/file/read-case ${pathnow}/${fluentcase}.cas" > ${jouname}.jou  #第一个为 '>' 表明覆盖,之后为追加
	echo "/file/read-data ${pathnow}/${fluentdata}.dat" >> ${jouname}.jou
	if [[ ${1} == 1 ]]; then
		echo "/solve/dual-time-iterate ${steps} ${maxits}" >> ${jouname}.jou
	else	
		echo "/solve/iterate ${steps}" >> ${jouname}.jou
	fi
	echo "exit" >> ${jouname}.jou
	echo "yes" >> ${jouname}.jou
	echo ""
}
usage(){
	echo "usage: vvg [ubuntu] [jiqun]"
}


printSettings(){
	#询问稳态还是非稳态
	while true; do
	    read -p "The time solve is Transient? (empty for 'yes')" yn
	    case $yn in
	        "" ) echo "**********Transient**********";istransient=1; break;;
	        [Yy]* ) echo "**********Transient**********";istransient=1; break;;
	        [Nn]* ) echo "**********steady**********"; istransient=0; break;;
	        * ) echo "Please answer yes or no.";;
	    esac
	done
	#读取case名
	echo -n "please input cas name (empty for 'fluent'):"
	read nametemp
	fluentcase=${nametemp:=fluent}
	#读取data名
	echo -n "please input data name (empty for '${fluentcase}'):"
	read nametemp
	fluentdata=${nametemp:=${fluentcase}}
	#2d or 3d
	echo -n "2d/3d/2ddp/3ddp(empty for '2ddp'):"
	read nametemp
	while true; do
		case ${nametemp} in
			"") is2d3d='2ddp';break;;
			2d | 3d | 2ddp | 3ddp) is2d3d=${nametemp};break;;
			*) echo "Please answer 2d/3d/2ddp/3ddp.";read nametemp;;
		esac
	done

	if [[ ${1} == 1 ]]; then
		#读取job名
		echo -n "please input jobname ('${fluentcase}'):"

		read nametemp
		jobname=${nametemp:=${fluentcase}}
	fi

	#读取cpu数
	echo -n "please input cpu number ('8'):"
	read numtemp
	number=${numtemp:=8}

	if [[ ${istransient} == 1 ]]; then
		#读取steps名
		echo -n "please input number of timesteps ('1000'):"
		read numtemp
		steps=${numtemp:=1000}

		#读取maxits名
		echo -n "please input max iterates of one step ('40'):"
		read numtemp
		maxits=${numtemp:=40}
	elif [[ ${istransient} == 0 ]]; then
		#读取steps名
		echo -n "please input number of iterations ('10000'):"
		read numtemp
		steps=${numtemp:=10000}
	fi
	
	#读取lsf名或sh名
	echo -n "please input sh name or lsf name ('fluent'):"
	read nametemp
	lsfname=${nametemp:=fluent}
	shname=${lsfname}

	if [[ ${istransient} == 1 ]]; then
		#读取jou名
		echo -n "please input jou name ('fluent-shuntai'):"
		read nametemp
		jouname=${nametemp:=fluent-shuntai}
	elif [[ ${istransient} == 0 ]]; then
			#读取jou名
		echo -n "please input jou name ('fluent-wentai'):"
		read nametemp
		jouname=${nametemp:=fluent-wentai}
	fi

	echo ""
	echo "**********settings**********";
}

#main,从这里开始主程序
case ${option1} in
	-h) usage
		;;
	--help) usage
		;;
	ubuntu) 
		printSettings
		WriteShfJou ${istransient}
		`chmod +x ${shname}.sh`
		echo `./${shname}.sh`
		;;
	jiqun) 
		printSettings ${isjiqun}
		WriteLsfJou ${istransient}
		echo `bsub < ${lsfname}.lsf`
		;;
	"") 
		printSettings
		WriteShfJou ${istransient}
		echo "the default is use 'vvg ubuntu'"
		echo "if you want to submit a lsf file, you need type 'bsub < ${lsfname}.lsf' after settings or use 'vvg jiqun'"
		echo ""
		echo "run './${shname}.sh' for calculation"
		;;
	*) 
		echo "Unknown opition: ${option1}"
		usage
		;;
esac

exit 0
